mode: all
min_length: 3
ignore_files:
  - '*test.go'
allowed:
  - aspell
  - repo
  - failsafe
  - golang
  - mkdir
  - apk
  - ubuntu
  - golangci
  - splitted
  - mri
  - IID
  - repo
  - OPTIM
  - Submatch
  - Lshortfile
  - MAXSUBJECTLEN
  - MAXSUBJECTPARTS
  - MINSUBJECTLEN
  - MINSUBJECTPARTS
  - malformatted
  - cmdline
  - sed
  - runnumber
  - LLC
  - devel
  - ioutil
  - defaultconf
  - json
  - req
  - nallowed
  - url
  - english
  - lang
  - junit
  - deps
  - alternative
  - awk
  - betteralign
  - cmd
  - cmds
  - cyclomatic
  - desc
  - dotenv
  - eval
  - fmt
  - formatter
  - gobin
  - gofumpt
  - gotestsum
  - govulncheck
  - hivis
  - linters
  - Printf
  - Println
  - staticcheck
  - struct
  - structs
  - taskfile
  - testdox
  - tmp
  - toml
  - unexported
  - unhandled
  - yml
